### PR TITLE
Issue #19 Fix JSON parsing of startResult

### LINKED ISSUE #19: Error message on cluster start
### CRC version 

1.22.0

### Description

Starting the cluster from the tray, the cluster is started properly but an error is shown:

crc_1 22 0_tray_error

Here is the [full log](https://gist.github.com/adrianriobo/ac238659d2c8b3b56f167620cab91c7e#file-error-log)

### LINKED ISSUE #20: Detailed status window information not updated
### CRC version

1.22.0

### Description

When starting the cluster from the tray the status detailed window information is never updated. It always shows empty values:

crc_1 22 0_tray_detailed_status_not_updated

### PR DESCRIPTION
**Pull request by anjannath**
Handle JSON parsing exception in start handler
Increase the size of byte array used to receive
response from daemon

Fixes #19 
Fixes #20

### CODE REVIEW

File: DaemonCommander/ResponseClasses.cs [hunk 1]
```diff
@@ -24,10 +24,20 @@ public class StartResult
 
     public class ClusterConfig
     {
+        public string ClusterCACert { get; set; }
```
Comment (cfergeau) [inline DaemonCommander/ResponseClasses.cs:27]: This commit is doing 3 different things, without explicit references to the initial bug, so it's very hard to know which of these 3 changes is the root cause of the bug and which ones are code/robustness improvements, or if all 3 are needed to fix the bug. Having an explanation of what exactly was causing the bug is likely to be useful if a similar bug occurs in a few months.

File: DaemonCommander/DaemonCommander.cs [hunk 2]
```diff
@@ -161,7 +161,7 @@ private string SendCommand(string command)
 		{
 			try
 			{
-				var resp = new byte[2048];
+				var resp = new byte[16 * 1048];
```
Comment (guillaumerose) [inline DaemonCommander/DaemonCommander.cs:164]: We should really change the protocol. Either to size + payload, http, grpc or something else.

Comment (cfergeau) [reply DaemonCommander/DaemonCommander.cs:164]: Even with size + payload, we'll need to only accept messages up to a given size, so similar bugs could happen (maximum size too small needing to be raised).

Comment (guillaumerose) [reply DaemonCommander/DaemonCommander.cs:164]: we can accept an int, then accept sizeof(the previous int). This what I do in gvisor-tap-vsock.

Comment (cfergeau) [reply DaemonCommander/DaemonCommander.cs:164]: But we cannot blindly trust this int, we don't want to blindly do 2GB allocations because some other process told us to do so.

Comment (cfergeau) [reply DaemonCommander/DaemonCommander.cs:164]: Btw, `1048` should be `1024` or `2048` I guess?

File: DaemonCommander/ResponseClasses.cs (hunk 1 above)
Comment (gbraad) [reply DaemonCommander/ResponseClasses.cs:27]: Perhaps 2 commits, as the Response just adds additional expected fields.

File: DaemonCommander/DaemonCommander.cs (hunk 2 above)
Comment (gbraad) [reply DaemonCommander/DaemonCommander.cs:164]: > which means the same issue is still present.

but for now less likely to encounter, in need of a follow-up permanent fix.
suggestions?

Comment (anjannath) [reply DaemonCommander/DaemonCommander.cs:164]: I thought it'd be better to move to the HTTP protocol, once its merged in crc () for now thought we need to increase the size to temporarily fix the bug.

Comment (cfergeau) [reply DaemonCommander/DaemonCommander.cs:164]: Yup, seems quick enough to have this fix for now, with the http work as a better fix later.

File: DaemonCommander/ResponseClasses.cs (hunk 1 above)
Comment (anjannath) [reply DaemonCommander/ResponseClasses.cs:27]: I split the commits.

**Review by cfergeau — APPROVED** [review]
:+1:
