### PR TITLE
Use `TryTaskWithRetry` to check if pull secret is set

### LINKED ISSUE #130: Implement a `TryTask(WithRetry = True)` to allow failing calls to be retried
The likely cause of the failing pull-secret call is related to the way the namedpipe and webclient interact. At times, the async task gets canceelled.

#128

### PR DESCRIPTION
**Pull request by anjannath**
- Add TryTaskWithRetry helper method to retry tasks that are canceled or times out
- Use TryTaskWithRetry to check if pull secret is set. Show a error notification in case `RetryableTaskFailedException` is thrown

Closes #130 #128

### CODE REVIEW

File: Helpers/TaskHelpers.cs [hunk 1]
```diff
@@ -1,28 +1,65 @@
...
+            for(; ;)
+            {
+                if(RetryCount > Count)
+                {
+                    throw new RetryableTaskFailedException($"Re-tried task {Count} times");
+                }
+
+                try
+                {
+                    return await TryTask(function, retryable: true);
```
Comment (anjannath) [inline Helpers/TaskHelpers.cs:37]: Reused `TryTask` but had to introduce the `retryable` parameter, with this we skip handling `TimeoutException` and `TaskCanceledException` in `handleAggregate

File: Helpers/TaskHelpers.cs [hunk 2]
```diff
@@ -1,28 +1,65 @@
...
             catch (AggregateException ae)
             {
-                handleAggregate(ae);
+                handleAggregate(ae, retryable: retryable);
             }
 
             return default;
         }
 
+        public static async Task<T> TryTaskWithRetry<T>(Func<T> function, int Count = 3, int backOff = 2000)
```
Comment (gbraad) [inline Helpers/TaskHelpers.cs:24]: `s/Count/Attempts`, and use a consistent capItalIzatIon

File: Helpers/TaskHelpers.cs [hunk 3]
```diff
@@ -94,15 +131,17 @@ private static void handleAggregateWithNotify(string failureMessage, string canc
...
-                        TrayIcon.NotifyError(
-$@"{failureMessage}
-{x.Message}");
+                        TrayIcon.NotifyError($@"{failureMessage} {x.Message}");
 
                     return true;
                 }
 
+                if (retryable)
+                    return false;
```
Comment (gbraad) [inline Helpers/TaskHelpers.cs:140]: Explain what this does. It does not mark the timeout contained in the aggregate as handled.

File: Helpers/TaskHelpers.cs [hunk 4]
```diff
@@ -94,15 +131,17 @@ private static void handleAggregateWithNotify(string failureMessage, string canc
...
+
                 if (x is TimeoutException || x is TaskCanceledException)
                 {
+                    Console.WriteLine("Exception:", x.ToString());
```
Comment (gbraad) [inline Helpers/TaskHelpers.cs:144]: Do we need this?

**Review by gbraad — CHANGES_REQUESTED** [review]
Some minor changes

File: Helpers/TaskHelpers.cs [hunk 5]
```diff
@@ -1,28 +1,65 @@
...
+using System.Threading;
 using System.Threading.Tasks;
 using CRCTray.Communication;
 
 namespace CRCTray.Helpers
 {
     internal class TaskHelpers
     {
-        public static async Task<T> TryTask<T>(Func<T> function)
+        public static async Task<T> TryTask<T>(Func<T> function, bool retryable = false)
```
Comment (gbraad) [inline Helpers/TaskHelpers.cs:10]: I would not introduce this as a public function. Setting the `retryable` will not yield the expected results.

```cs
public static async Task<T> TryTask<T>(Func<T> function) {
{
    return await TryTask(function, false);
}

private static async Task<T> TryTask<T>(Func<T> function, bool retryable)
{
...
```

**Review by gbraad — CHANGES_REQUESTED** [review]
Modified public API with a parameter that might cause unexpected side-effects when set

File: Helpers/TaskHelpers.cs (hunk 3 above)
Comment (gbraad) [reply Helpers/TaskHelpers.cs:140]: Naming is confusing, as mentioned on the call we had. It does not convey the actual intent.

File: CRCTray.cs [hunk 6]
```diff
@@ -237,28 +237,37 @@ async private void StartMenu_Click(object sender, EventArgs e)
...
+                    if (pullSecretContent == String.Empty)
+                    {
+                        TrayIcon.NotifyWarn(@"No Pull Secret was provided. Cannot start cluster without pull secret.");
+                        return;
+                    }
+
+                    TaskHelpers.TryTask(Tasks.SendTelemetry, Actions.EnterPullSecret).NoAwait();
+
+                    // Store pullsecret; returns false is not able to
+                    var stored = await TaskHelpers.TryTask(Tasks.SetPullSecret, pullSecretContent);
```
Comment (gbraad) [inline CRCTray.cs:258]: Wouldn't this be impacted by taskcanceled too?

**Review by gbraad — CHANGES_REQUESTED** [review]
Get is now wrapped, but Set is not?

File: CRCTray.cs [hunk 7]
```diff
@@ -237,28 +237,37 @@ async private void StartMenu_Click(object sender, EventArgs e)
...
+                    if (!stored)
+                    {
+                        TrayIcon.NotifyError(@"Pull-secret not stored. Please check if valid format is used.");
+                        return;
+                    }
 
+                }
+            }
+            catch (RetryableTaskFailedException ex)
```
Comment (gbraad) [inline CRCTray.cs:267]: This try-catch-block wraps too much. Only the `TryTaskWithRetry` needs this. The `return` will break the function anyway, so it is not like you prevent code execution.

File: CRCTray.cs (hunk 6 above)
Comment (anjannath) [reply CRCTray.cs:258]: Should we use `TryTaskWithRetry` for all the the calls as all of them has a chance of getting cancelled..

File: CRCTray.cs (hunk 7 above)
Comment (anjannath) [reply CRCTray.cs:267]: Its because of the scope of the tray block, we need to use the result of the task, so wanted to avoid the declaration of `pullsecret` outside the tray-catch.

Comment (gbraad) [reply CRCTray.cs:245]: perhaps better to declare as:

```cs
            bool pullsecretExists = false;
            try
            {
                pullsecretExists = await TaskHelpers.TryTaskWithRetry(Tasks.GetPullSecret);
            }
```

File: CRCTray.cs [hunk 8]
```diff
@@ -253,12 +262,11 @@ async private void StartMenu_Click(object sender, EventArgs e)
 
                 // Store pullsecret; returns false is not able to
                 var stored = await TaskHelpers.TryTask(Tasks.SetPullSecret, pullSecretContent);
```
Comment (gbraad) [inline CRCTray.cs:264]: and in that case

```
            bool pullsecretStored = false;
            try
            {
                pullsecretStored = await TaskHelpers.TryTask(Tasks.SetPullSecret, pullSecretContent);
            }
            catch(...
```

as the same issue can occur here

**Review by gbraad — CHANGES_REQUESTED** [review]
Rename variables and make sure the Set is also retried.

**Comment by anjannath** [comment]
@gbraad Updated, PTALA!

File: CRCTray.cs [hunk 9]
```diff
@@ -252,13 +261,22 @@ async private void StartMenu_Click(object sender, EventArgs e)
...
-                var stored = await TaskHelpers.TryTask(Tasks.SetPullSecret, pullSecretContent);
-                if(!stored)
+                bool pullsecretStored = false;
+                try
+                {
+                    pullsecretStored = await TaskHelpers.TryTaskWithRetry(Tasks.SetPullSecret, pullSecretContent);
+                }
+                catch (RetryableTaskFailedException ex)
+                {
+                    TrayIcon.NotifyError($"Failed to store pull secret. {ex.Message}. You'll be asked to enter it again on next start.");
```
Comment (gbraad) [inline CRCTray.cs:271]: Not a bad message

**Review by gbraad — APPROVED** [review]
